"""
Data schemas for Bedrock service
"""
from typing import List, Dict, Any, Optional
from decimal import Decimal
from dataclasses import dataclass, asdict


@dataclass
class ClinicalSummary:
    """Clinical summary generated by Bedrock"""
    emotional_state: str
    verbal_content_analysis: Optional[str] = None
    medication_adherence: str = ""
    risk_assessment: str = "low"  # "low", "moderate", "high"
    risk_factors: List[str] = None
    recommendations: List[str] = None
    clinical_notes: str = ""
    confidence: Decimal = Decimal('0.0')
    generated_by: str = "aws_bedrock_claude_3_haiku"
    model_version: str = "anthropic.claude-3-haiku-20240307-v1:0"
    
    def __post_init__(self):
        """Initialize default values for mutable fields"""
        if self.risk_factors is None:
            self.risk_factors = []
        if self.recommendations is None:
            self.recommendations = []
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return asdict(self)
    
    def validate(self) -> bool:
        """Validate required fields"""
        if not self.emotional_state:
            return False
        if not self.medication_adherence:
            return False
        if self.risk_assessment not in ['low', 'moderate', 'high']:
            return False
        if not isinstance(self.recommendations, list) or len(self.recommendations) == 0:
            return False
        return True


@dataclass
class EmotionData:
    """Input emotion data structure"""
    audio_emotion: Dict[str, Any]
    facial_emotion: Dict[str, Any]
    compliance: Optional[Dict[str, Any]] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            'audio_emotion': self.audio_emotion,
            'facial_emotion': self.facial_emotion,
            'compliance': self.compliance or {}
        }


@dataclass
class BedrockUsage:
    """Token usage and cost tracking"""
    input_tokens: int
    output_tokens: int
    model: str = "claude-3-haiku"
    
    @property
    def total_tokens(self) -> int:
        """Total tokens used"""
        return self.input_tokens + self.output_tokens
    
    @property
    def cost_usd(self) -> Decimal:
        """Calculate cost in USD (Haiku pricing)"""
        input_cost = Decimal(self.input_tokens) / Decimal(1_000_000) * Decimal('0.25')
        output_cost = Decimal(self.output_tokens) / Decimal(1_000_000) * Decimal('1.25')
        return input_cost + output_cost
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            'input_tokens': self.input_tokens,
            'output_tokens': self.output_tokens,
            'total_tokens': self.total_tokens,
            'cost_usd': float(self.cost_usd),
            'model': self.model
        }


# Example schemas for reference
EXAMPLE_EMOTION_DATA = {
    "audio_emotion": {
        "primary_emotion": "angry",
        "confidence": 0.68,
        "all_emotions": {
            "angry": 0.68,
            "sad": 0.12,
            "neutral": 0.10,
            "happy": 0.06,
            "fearful": 0.04
        }
    },
    "facial_emotion": {
        "primary_emotion": "happy",
        "confidence": 0.48,
        "all_emotions": {
            "happy": 0.48,
            "sad": 0.31,
            "angry": 0.12,
            "neutral": 0.09
        },
        "face_detected": True
    },
    "compliance": {
        "pill_detected": True,
        "compliance_score": 0.85,
        "verification_status": "compliant"
    }
}

EXAMPLE_CLINICAL_SUMMARY = {
    "emotional_state": "Patient displays emotional incongruence with angry audio tone (68%) contrasting happy facial expression (48%). This discordance may suggest emotional masking or internal distress.",
    "medication_adherence": "Video evidence confirms medication intake with clear pill consumption observed. Compliance score of 85% indicates good adherence.",
    "risk_assessment": "moderate",
    "risk_factors": [
        "Emotional incongruence between audio and facial expressions",
        "Elevated anger levels in voice tone"
    ],
    "recommendations": [
        "Schedule follow-up within 48 hours to assess emotional state",
        "Conduct clinical interview to explore potential anger triggers",
        "Monitor for signs of emotional suppression or masking behavior",
        "Consider assessment for mood disorders if pattern persists"
    ],
    "clinical_notes": "The significant mismatch between audio anger and facial happiness warrants closer monitoring. Patient may be experiencing internal emotional distress not reflected in outward expression.",
    "confidence": 0.87,
    "generated_by": "aws_bedrock_claude_3_haiku",
    "model_version": "anthropic.claude-3-haiku-20240307-v1:0"
}
